name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  Security_Analizy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Scaneando código com SonarQube
      uses: SonarSource/sonarqube-scan-action@v4.2.1
      with:
        args: >
          -Dsonar.organization=FakeShop
          -Dsonar.projectKey=fake-shop
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  CI:
    runs-on: ubuntu-latest
    needs: [ Security_Analizy ]
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4.2.2

      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construção e envio da imagem Docker
        uses: docker/build-push-action@v6.12.0
        with:
          context: ./src
          push: true
          file: src/Dockerfile
          tags: |
            davidlimacd/fake-shop:v${{ github.run_number }}
            davidlimacd/fake-shop:latest
  
  CD:
    runs-on: ubuntu-latest
    needs: [ CI ]
    permissions:
      id-token: write
      contents: read
      actions: read
      
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4.2.2

      - name: Autenticar na AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/${{ vars.AWS_ROLE }}
          aws-region: us-east-1

      - name: Configurar o kubectl
        run: aws eks update-kubeconfig --name ${{ vars.AWS_EKS_CLUSTER }}

      - name: Deploy dos manifestos no Kubernets
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
              ./k8s/fakeshop_deployment.yaml
          images: davidlimacd/fake-shop:v${{ github.run_number }}
      
      - name: Deploy do Prometheus e Grafana
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
              ./k8s/monitoring_deployment.yaml